// <auto-generated />
using System;
using Game.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Server.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Game.Shared.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvancedProfessionCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackTalentRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthTalentRank")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TalentHealingDonePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TalentHealingReceivedPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TalentMaxHpPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TalentNormalAttackPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TalentSkillCriticalChancePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TalentSkillDamagePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeaponAttackBonusPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeaponCriticalChancePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeaponHealthBonusPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeaponStaminaPercent").HasColumnType("TEXT");
                    b.Property<decimal>("WeaponEnmityPercent").HasColumnType("TEXT");
                    b.Property<decimal>("WeaponDoubleAttackChancePercent").HasColumnType("TEXT");
                    b.Property<decimal>("WeaponNormalEchoPercent").HasColumnType("TEXT");
                    b.Property<decimal>("WeaponSkillDamagePercent").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterItemStack", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("ItemCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "ItemCode").IsUnique();
                    b.ToTable("CharacterItemStacks", t => t.HasCheckConstraint("CK_CharacterItemStacks_Quantity", "Quantity >= 0"));
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterWeapon", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("WeaponCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("TemplateRevision").HasColumnType("INTEGER");
                    b.Property<string>("Origin").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Element").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Attack").HasColumnType("INTEGER");
                    b.Property<int>("MaxHp").HasColumnType("INTEGER");
                    b.Property<int>("ItemLevel").HasColumnType("INTEGER");
                    b.Property<int>("SellGold").HasColumnType("INTEGER");
                    b.Property<int>("DismantleFragments").HasColumnType("INTEGER");
                    b.Property<bool>("IsLocked").HasColumnType("INTEGER");
                    b.Property<int?>("EquippedSlotIndex").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "EquippedSlotIndex").IsUnique().HasFilter("EquippedSlotIndex IS NOT NULL");
                    b.ToTable("CharacterWeapons", t =>
                    {
                        t.HasCheckConstraint("CK_CharacterWeapons_Progression", "ItemLevel > 0");
                        t.HasCheckConstraint("CK_CharacterWeapons_Recycling", "SellGold >= 0 AND DismantleFragments > 0");
                        t.HasCheckConstraint("CK_CharacterWeapons_Stats", "Attack >= 0 AND MaxHp > 0");
                        t.HasCheckConstraint("CK_CharacterWeapons_Slot", "EquippedSlotIndex IS NULL OR EquippedSlotIndex BETWEEN 1 AND 10");
                    });
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterWeaponSkill", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("WeaponId").HasColumnType("INTEGER");
                    b.Property<int>("SlotIndex").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Level").HasColumnType("INTEGER");
                    b.Property<int>("BaseLevel").HasColumnType("INTEGER");
                    b.Property<int>("QualityBonusLevel").HasColumnType("INTEGER");
                    b.Property<int>("EnhancementLevel").HasColumnType("INTEGER");
                    b.Property<int?>("SpentFragments").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("WeaponId", "SlotIndex").IsUnique();
                    b.HasIndex("WeaponId", "SkillCode").IsUnique();
                    b.ToTable("CharacterWeaponSkills", t =>
                    {
                        t.HasCheckConstraint("CK_CharacterWeaponSkills_Level", "Level BETWEEN 1 AND 20");
                        t.HasCheckConstraint("CK_CharacterWeaponSkills_Progression", "BaseLevel BETWEEN 1 AND 20 AND QualityBonusLevel BETWEEN 0 AND 3 AND EnhancementLevel BETWEEN 0 AND 3 AND Level = BaseLevel + QualityBonusLevel + EnhancementLevel");
                        t.HasCheckConstraint("CK_CharacterWeaponSkills_Slot", "SlotIndex BETWEEN 1 AND 3");
                    });
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterConsumableSlot", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<int>("SlotIndex").HasColumnType("INTEGER");
                    b.Property<string>("ItemCode").HasColumnType("TEXT");
                    b.Property<bool>("AutoUseEnabled").HasColumnType("INTEGER");
                    b.Property<int>("AutoHpThresholdPercent").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "SlotIndex").IsUnique();
                    b.ToTable("CharacterConsumableSlots", t => t.HasCheckConstraint("CK_CharacterConsumableSlots_Threshold", "AutoHpThresholdPercent BETWEEN 1 AND 100"));
                });

            modelBuilder.Entity("Game.Shared.Models.BattleConsumableCooldown", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("CooldownGroup").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ReadyAtRound").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "CharacterId", "CooldownGroup").IsUnique();
                    b.ToTable("BattleConsumableCooldowns");
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterSkillSlot", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<int>("SlotIndex").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").HasColumnType("TEXT");
                    b.Property<bool>("AutoUseEnabled").HasColumnType("INTEGER");
                    b.Property<int>("AutoHpThresholdPercent").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "SlotIndex").IsUnique();
                    b.ToTable("CharacterSkillSlots", t => t.HasCheckConstraint("CK_CharacterSkillSlots_Threshold", "AutoHpThresholdPercent BETWEEN 1 AND 100"));
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterSkillTalent", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("NodeCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("PointsSpent").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "NodeCode").IsUnique();
                    b.ToTable("CharacterSkillTalents", t => t.HasCheckConstraint("CK_CharacterSkillTalents_PointsSpent", "PointsSpent > 0"));
                });

            modelBuilder.Entity("Game.Shared.Models.BattleSkillCooldown", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ReadyAtRound").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "CharacterId", "SkillCode").IsUnique();
                    b.ToTable("BattleSkillCooldowns");
                });

            modelBuilder.Entity("Game.Shared.Models.BattleMonsterSkillCooldown", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("MonsterId").HasColumnType("INTEGER");
                    b.Property<int>("ReadyAtRound").HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "MonsterId", "SkillCode").IsUnique();
                    b.ToTable("BattleMonsterSkillCooldowns");
                });

            modelBuilder.Entity("Game.Shared.Models.BattleStatusEffect", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("AppliedRound").HasColumnType("INTEGER");
                    b.Property<string>("EffectCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ExpiresAfterRound").HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("RunSequence").HasColumnType("INTEGER");
                    b.Property<int>("Stacks").HasColumnType("INTEGER");
                    b.Property<int>("TargetId").HasColumnType("INTEGER");
                    b.Property<string>("TargetType").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "RunSequence", "TargetType", "TargetId", "EffectCode").IsUnique();
                    b.ToTable("BattleStatusEffects", t => t.HasCheckConstraint("CK_BattleStatusEffects_Values", "Stacks > 0 AND ExpiresAfterRound >= AppliedRound"));
                });

            modelBuilder.Entity("Game.Shared.Models.Dungeon", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Code").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DungeonKind").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsVisible").HasColumnType("INTEGER");
                    b.Property<int>("MinimumLevel").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("MonsterName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("MonsterElement").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("MonsterMaxHp").HasColumnType("INTEGER");
                    b.Property<int>("MonsterAttack").HasColumnType("INTEGER");
                    b.Property<int>("MonsterDefense").HasColumnType("INTEGER");
                    b.Property<int>("RecommendedLevel").HasColumnType("INTEGER");
                    b.Property<string>("RegionName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RegionCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("SlotCount").HasColumnType("INTEGER");
                    b.Property<int>("SortOrder").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("Code").IsUnique();
                    b.ToTable("Dungeons", t => t.HasCheckConstraint("CK_Dungeons_Levels", "MinimumLevel > 0 AND RecommendedLevel >= MinimumLevel"));
                });

            modelBuilder.Entity("Game.Shared.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CombatProfileCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardProfileCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WaveNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "WaveNumber", "Position")
                        .IsUnique()
                        .HasFilter("RoomId IS NOT NULL");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Game.Shared.Models.MonsterIntent", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ActionType").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<bool>("IsInterrupted").HasColumnType("INTEGER");
                    b.Property<int>("MonsterId").HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("RoundNumber").HasColumnType("INTEGER");
                    b.Property<int>("RunSequence").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").HasColumnType("TEXT");
                    b.Property<int?>("TargetCharacterId").HasColumnType("INTEGER");
                    b.Property<string>("TargetType").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "RunSequence", "RoundNumber", "MonsterId").IsUnique();
                    b.ToTable("MonsterIntents");
                });

            modelBuilder.Entity("Game.Shared.Models.RewardRun", b =>
                {
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("Sequence").HasColumnType("INTEGER");
                    b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("SettledAtUtc").HasColumnType("TEXT");
                    b.HasKey("RoomId", "Sequence");
                    b.ToTable("RewardRuns");
                });

            modelBuilder.Entity("Game.Shared.Models.RewardEvent", b =>
                {
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("Sequence").HasColumnType("INTEGER");
                    b.Property<string>("EventKey").HasColumnType("TEXT");
                    b.HasKey("RoomId", "Sequence", "EventKey");
                    b.ToTable("RewardEvents");
                });

            modelBuilder.Entity("Game.Shared.Models.RewardEntry", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("Sequence").HasColumnType("INTEGER");
                    b.Property<string>("EventKey").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("Kind").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Code").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<string>("WeaponSnapshotJson").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "Sequence", "UserId");
                    b.ToTable("RewardEntries", t => t.HasCheckConstraint("CK_RewardEntries_Quantity", "Quantity > 0"));
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterActivity", b =>
                {
                    b.Property<int>("CharacterId").ValueGeneratedNever().HasColumnType("INTEGER");
                    b.Property<string>("Kind").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("SourceId").HasColumnType("INTEGER");
                    b.Property<DateTime>("StartedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime?>("EndsAtUtc").HasColumnType("TEXT");
                    b.HasKey("CharacterId");
                    b.HasIndex("Kind", "SourceId");
                    b.ToTable("CharacterActivities");
                });

            modelBuilder.Entity("Game.Shared.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BattleEndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc").HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc").HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc").HasColumnType("TEXT");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentWaveNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepeatBattle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreparationTimeoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRoundAvailableAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundCooldownDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PreparationStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWaveCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Game.Shared.Models.RoomSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMainControl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporaryAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PendingConsumableSlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingSkillSlotMask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("RoomSlots");
                });

            modelBuilder.Entity("Game.Shared.Models.UserDungeonClear", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("ClearedAtUtc").HasColumnType("TEXT");
                    b.Property<int>("DungeonId").HasColumnType("INTEGER");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "DungeonId").IsUnique();
                    b.ToTable("UserDungeonClears");
                });

            modelBuilder.Entity("Game.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterSlotLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StarterWeaponRewardClaimed").HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Game.Shared.Models.UserLoginSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserLoginSessions");
                });

            modelBuilder.Entity("Game.Shared.Models.UserWarehouseStack", b =>
                {
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.Property<string>("ItemCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("UserId", "ItemCode");
                    b.ToTable("UserWarehouseStacks", t => t.HasCheckConstraint("CK_UserWarehouseStacks_Quantity", "Quantity >= 0"));
                });

            modelBuilder.Entity("Game.Shared.Models.WarehouseTransferRecord", b =>
                {
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.Property<string>("RequestId").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("ItemCode").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Direction").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("UserId", "RequestId");
                    b.ToTable("WarehouseTransferRecords");
                });
            modelBuilder.Entity("Game.Shared.Models.CharacterWeaponSkill", b =>
                {
                    b.HasOne("Game.Shared.Models.CharacterWeapon", null)
                        .WithMany("Skills")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterWeapon", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
