// <auto-generated />
using System;
using Game.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Server.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Game.Shared.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackTalentRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenseTalentRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthTalentRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterItemStack", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("ItemCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "ItemCode").IsUnique();
                    b.ToTable("CharacterItemStacks", t => t.HasCheckConstraint("CK_CharacterItemStacks_Quantity", "Quantity >= 0"));
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterWeapon", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("WeaponCode").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Element").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Attack").HasColumnType("INTEGER");
                    b.Property<int>("MaxHp").HasColumnType("INTEGER");
                    b.Property<int?>("EquippedSlotIndex").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "EquippedSlotIndex").IsUnique().HasFilter("EquippedSlotIndex IS NOT NULL");
                    b.ToTable("CharacterWeapons", t =>
                    {
                        t.HasCheckConstraint("CK_CharacterWeapons_Stats", "Attack >= 0 AND MaxHp > 0");
                        t.HasCheckConstraint("CK_CharacterWeapons_Slot", "EquippedSlotIndex IS NULL OR EquippedSlotIndex BETWEEN 1 AND 10");
                    });
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterConsumableSlot", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<int>("SlotIndex").HasColumnType("INTEGER");
                    b.Property<string>("ItemCode").HasColumnType("TEXT");
                    b.Property<bool>("AutoUseEnabled").HasColumnType("INTEGER");
                    b.Property<int>("AutoHpThresholdPercent").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "SlotIndex").IsUnique();
                    b.ToTable("CharacterConsumableSlots", t => t.HasCheckConstraint("CK_CharacterConsumableSlots_Threshold", "AutoHpThresholdPercent BETWEEN 1 AND 100"));
                });

            modelBuilder.Entity("Game.Shared.Models.BattleConsumableCooldown", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("CooldownGroup").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ReadyAtRound").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "CharacterId", "CooldownGroup").IsUnique();
                    b.ToTable("BattleConsumableCooldowns");
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterSkillSlot", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<int>("SlotIndex").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").HasColumnType("TEXT");
                    b.Property<bool>("AutoUseEnabled").HasColumnType("INTEGER");
                    b.Property<int>("AutoHpThresholdPercent").HasColumnType("INTEGER");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "SlotIndex").IsUnique();
                    b.ToTable("CharacterSkillSlots", t => t.HasCheckConstraint("CK_CharacterSkillSlots_Threshold", "AutoHpThresholdPercent BETWEEN 1 AND 100"));
                });

            modelBuilder.Entity("Game.Shared.Models.CharacterSkillTalent", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("NodeCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("PointsSpent").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CharacterId", "NodeCode").IsUnique();
                    b.ToTable("CharacterSkillTalents", t => t.HasCheckConstraint("CK_CharacterSkillTalents_PointsSpent", "PointsSpent > 0"));
                });

            modelBuilder.Entity("Game.Shared.Models.BattleSkillCooldown", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("RoomId").HasColumnType("INTEGER");
                    b.Property<int>("CharacterId").HasColumnType("INTEGER");
                    b.Property<string>("SkillCode").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ReadyAtRound").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("RoomId", "CharacterId", "SkillCode").IsUnique();
                    b.ToTable("BattleSkillCooldowns");
                });

            modelBuilder.Entity("Game.Shared.Models.Dungeon", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Code").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("MonsterName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("MonsterElement").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("MonsterMaxHp").HasColumnType("INTEGER");
                    b.Property<int>("MonsterAttack").HasColumnType("INTEGER");
                    b.Property<int>("MonsterDefense").HasColumnType("INTEGER");
                    b.Property<int>("SlotCount").HasColumnType("INTEGER");
                    b.Property<int>("SortOrder").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("Code").IsUnique();
                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("Game.Shared.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Game.Shared.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BattleEndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepeatBattle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreparationTimeoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRoundAvailableAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundCooldownDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PreparationStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Game.Shared.Models.RoomSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMainControl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporaryAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PendingConsumableSlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingSkillSlotMask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("RoomSlots");
                });

            modelBuilder.Entity("Game.Shared.Models.UserDungeonClear", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("ClearedAtUtc").HasColumnType("TEXT");
                    b.Property<int>("DungeonId").HasColumnType("INTEGER");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "DungeonId").IsUnique();
                    b.ToTable("UserDungeonClears");
                });

            modelBuilder.Entity("Game.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Game.Shared.Models.UserLoginSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserLoginSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
