// Generated by tools/build_item_manifest.py from the item catalog.
namespace Game.Client.Services;

public static class ItemArt
{
    private static readonly Dictionary<string, string> PathsByCode = new(StringComparer.Ordinal)
    {
        ["minor-healing-potion"] = "/art/items/potions/minor-healing-potion.png",
        ["northshire-battle-draught"] = "/art/items/potions/northshire-battle-draught.png",
        ["travel-healing-potion"] = "/art/items/potions/travel-healing-potion.png",
        ["whetstone-oil"] = "/art/items/potions/whetstone-oil.png",
        ["elwynn-assault-draught"] = "/art/items/potions/elwynn-assault-draught.png",
        ["tirisfal-dusk-draught"] = "/art/items/potions/tirisfal-dusk-draught.png",
        ["durotar-bloodfire-draught"] = "/art/items/potions/durotar-bloodfire-draught.png",
        ["dun-morogh-fortitude-draught"] = "/art/items/potions/dun-morogh-fortitude-draught.png",
        ["mulgore-hunter-draught"] = "/art/items/potions/mulgore-hunter-draught.png",
        ["eversong-inspiration-draught"] = "/art/items/potions/eversong-inspiration-draught.png",
        ["peacebloom"] = "/art/items/herbs/peacebloom.png",
        ["silverleaf"] = "/art/items/herbs/silverleaf.png",
        ["earthroot"] = "/art/items/herbs/earthroot.png",
        ["briarthorn"] = "/art/items/herbs/briarthorn.png",
        ["tirisfal-gravemoss"] = "/art/items/herbs/tirisfal-gravemoss.png",
        ["tirisfal-shadowvine"] = "/art/items/herbs/tirisfal-shadowvine.png",
        ["tirisfal-crypt-spore"] = "/art/items/herbs/tirisfal-crypt-spore.png",
        ["durotar-aloe"] = "/art/items/herbs/durotar-aloe.png",
        ["durotar-firethorn"] = "/art/items/herbs/durotar-firethorn.png",
        ["durotar-cinderroot"] = "/art/items/herbs/durotar-cinderroot.png",
        ["dun-morogh-frostdew"] = "/art/items/herbs/dun-morogh-frostdew.png",
        ["dun-morogh-springroot"] = "/art/items/herbs/dun-morogh-springroot.png",
        ["dun-morogh-icecap"] = "/art/items/herbs/dun-morogh-icecap.png",
        ["mulgore-sage"] = "/art/items/herbs/mulgore-sage.png",
        ["mulgore-windbell"] = "/art/items/herbs/mulgore-windbell.png",
        ["mulgore-stormseed"] = "/art/items/herbs/mulgore-stormseed.png",
        ["eversong-goldleaf"] = "/art/items/herbs/eversong-goldleaf.png",
        ["eversong-dawnflower"] = "/art/items/herbs/eversong-dawnflower.png",
        ["eversong-sunpetal"] = "/art/items/herbs/eversong-sunpetal.png",
    };

    public static string? ForCode(string? code) => code is not null && PathsByCode.TryGetValue(code, out var path)
        ? path : null;
}
