// Generated by tools/build_profession_manifest.py from the profession catalog.
namespace Game.Client.Services;

public static class ProfessionArt
{
    private static readonly Dictionary<string, string> PathsByCode = new(StringComparer.Ordinal)
    {
        ["swordsman"] = "/art/professions/swordsman.png",
        ["acolyte"] = "/art/professions/acolyte.png",
        ["mage"] = "/art/professions/mage.png",
        ["hunter"] = "/art/professions/hunter.png",
        ["rogue"] = "/art/professions/rogue.png",
    };

    private static readonly Dictionary<string, string> CodesByName = new(StringComparer.Ordinal)
    {
        ["骑士"] = "swordsman",
        ["祭司"] = "acolyte",
        ["法师"] = "mage",
        ["猎人"] = "hunter",
        ["盗贼"] = "rogue",
    };

    public static string ForCode(string? code) => code is not null && PathsByCode.TryGetValue(code, out var path)
        ? path : "/art/professions/swordsman.png";

    public static string ForName(string? name) => name is not null && CodesByName.TryGetValue(name, out var code)
        ? ForCode(code) : ForCode(null);
}
