// Generated by tools/build_skill_manifest.py from the skill catalog.
namespace Game.Client.Services;

public static class SkillArt
{
    private static readonly Dictionary<string, string> PathsByCode = new(StringComparer.Ordinal)
    {
        ["sword-slash"] = "/art/skills/sword-slash.png",
        ["knight-faith-barrier"] = "/art/skills/knight-guard.png",
        ["knight-rebuke"] = "/art/skills/sword-intercept.png",
        ["knight-invigorate"] = "/art/skills/knight-invigorate.png",
        ["knight-holy-aura"] = "/art/skills/knight-holy-aura.png",
        ["acolyte-holy-bolt"] = "/art/skills/acolyte-holy-bolt.png",
        ["acolyte-heal"] = "/art/skills/acolyte-heal.png",
        ["acolyte-purify"] = "/art/skills/acolyte-purify.png",
        ["acolyte-group-heal"] = "/art/skills/priest-group-heal.png",
        ["acolyte-revelation"] = "/art/skills/acolyte-radiant-flare.png",
        ["mage-arcane-bolt"] = "/art/skills/mage-arcane-bolt.png",
        ["mage-frost-bolt"] = "/art/skills/mage-frost-bolt.png",
        ["mage-scorch"] = "/art/skills/elementalist-pyroblast.png",
        ["mage-spellbreak"] = "/art/skills/mage-spellbreak.png",
        ["mage-arcane-domain"] = "/art/skills/mage-arcane-domain.png",
        ["hunter-tracking-shot"] = "/art/skills/hunter-marked-shot.png",
        ["hunter-precision-shot"] = "/art/skills/hunter-quick-shot.png",
        ["hunter-expose-shot"] = "/art/skills/hunter-expose-shot.png",
        ["hunter-hunting-signal"] = "/art/skills/hunter-hunting-signal.png",
        ["hunter-eagle-eye"] = "/art/skills/hunter-eagle-eye.png",
        ["rogue-shadow-strike"] = "/art/skills/rogue-shadow-strike.png",
        ["rogue-execution-slash"] = "/art/skills/rogue-gouge.png",
        ["rogue-poisoned-blade"] = "/art/skills/rogue-poisoned-blade.png",
        ["rogue-adrenaline"] = "/art/skills/rogue-adrenaline.png",
        ["rogue-blade-flurry"] = "/art/skills/rogue-blade-flurry.png",
    };

    public static string? ForCode(string? code) => code is not null && PathsByCode.TryGetValue(code, out var path)
        ? path : null;
}
