// Generated by tools/build_skill_manifest.py from the skill catalog.
namespace Game.Client.Services;

public static class SkillArt
{
    private static readonly HashSet<string> Codes = new(StringComparer.Ordinal)
    {
        "sword-slash",
        "sword-parry",
        "sword-double-slash",
        "sword-intercept",
        "acolyte-holy-bolt",
        "acolyte-heal",
        "acolyte-silence",
        "acolyte-purify",
        "acolyte-radiant-flare",
        "knight-guard",
        "warrior-fury",
        "priest-group-heal",
        "mage-arcane-bolt",
        "mage-frost-ward",
        "mage-arcane-barrage",
        "mage-spellbreak",
        "mage-arcane-suppression",
        "hunter-quick-shot",
        "hunter-field-mend",
        "hunter-marked-shot",
        "hunter-venom-arrow",
        "hunter-rapid-volley",
        "rogue-shadow-strike",
        "rogue-evasion",
        "rogue-blade-flurry",
        "rogue-poisoned-blade",
        "rogue-gouge",
        "inquisitor-condemn",
        "elementalist-pyroblast",
        "arcanist-overcharge",
        "marksman-sniper-shot",
        "beastmaster-coordinated-assault",
        "assassin-deathblow",
        "trickster-smoke-bomb",
    };

    public static string? ForCode(string? code) => code is not null && Codes.Contains(code)
        ? $"/art/skills/{code}.png" : null;
}
