"""Validate class art subjects and generate the client class-art lookup."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "Game.Server" / "appsettings.json"
SUBJECTS = ROOT / "assets" / "profession-art" / "subjects.json"
MANIFEST = ROOT / "assets" / "profession-art" / "manifest.json"
SERVICE = ROOT / "Game.Client" / "Services" / "ProfessionArt.cs"


def main() -> None:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    subjects = json.loads(SUBJECTS.read_text(encoding="utf-8"))
    professions = {item["Code"]: item for item in config["Skills"]["Professions"]}
    planned = {item["code"]: item for item in subjects}
    if professions.keys() != planned.keys():
        raise ValueError(f"missing={professions.keys() - planned.keys()}, extra={planned.keys() - professions.keys()}")

    entries = []
    for item in subjects:
        profession = professions[item["code"]]
        entries.append({"code": item["code"], "name": profession["Name"],
                        "base": profession.get("BaseProfessionCode"),
                        "file": f"{item['code']}.png", "subject": item["subject"]})
    MANIFEST.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = ["// Generated by tools/build_profession_manifest.py from the profession catalog.",
             "namespace Game.Client.Services;", "", "public static class ProfessionArt", "{",
             "    private static readonly Dictionary<string, string> PathsByCode = new(StringComparer.Ordinal)",
             "    {"]
    for item in entries:
        lines.append(f'        ["{item["code"]}"] = "/art/professions/{item["file"]}",')
    lines += ["    };", "", "    private static readonly Dictionary<string, string> CodesByName = new(StringComparer.Ordinal)", "    {"]
    for item in entries:
        lines.append(f'        ["{item["name"]}"] = "{item["code"]}",')
    lines += ["    };", "", "    public static string ForCode(string? code) => code is not null && PathsByCode.TryGetValue(code, out var path)",
              '        ? path : "/art/professions/swordsman.png";', "",
              "    public static string ForName(string? name) => name is not null && CodesByName.TryGetValue(name, out var code)",
              "        ? ForCode(code) : ForCode(null);", "}"]
    SERVICE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(entries)} professions")


if __name__ == "__main__":
    main()
