"""Validate the encounter art catalog and generate the client name lookup."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SUBJECTS = ROOT / "assets" / "monster-art" / "subjects.json"
ENCOUNTERS = ROOT / "Game.Server" / "appsettings.json"
MANIFEST = ROOT / "assets" / "monster-art" / "manifest.json"
CLIENT_MAP = ROOT / "Game.Client" / "Services" / "MonsterArt.cs"


def main() -> None:
    subjects = json.loads(SUBJECTS.read_text(encoding="utf-8"))
    encounters = json.loads(ENCOUNTERS.read_text(encoding="utf-8"))["DungeonEncounters"]["Dungeons"]
    elements = {}
    for waves in encounters.values():
        for wave in waves:
            for monster in wave["Monsters"]:
                name, element = monster["Name"], monster["Element"]
                if name in elements and elements[name] != element:
                    raise ValueError(f"Conflicting elements for {name}")
                elements[name] = element
    if set(elements) != set(subjects):
        raise ValueError(f"Subject mismatch: missing={set(elements)-set(subjects)}, extra={set(subjects)-set(elements)}")

    manifest = [
        {"name": name, "file": f"monster-{index:03d}.png", "element": elements[name], "subject": subject}
        for index, (name, subject) in enumerate(subjects.items(), 1)
    ]
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = [
        "// Generated by tools/build_monster_manifest.py from the encounter catalog.",
        "namespace Game.Client.Services;",
        "",
        "public static class MonsterArt",
        "{",
        "    private static readonly Dictionary<string, string> FilesByName = new(StringComparer.Ordinal)",
        "    {",
    ]
    for item in manifest:
        lines.append(f'        ["{item["name"]}"] = "{item["file"]}",')
    lines += [
        "    };",
        "",
        "    public static string ForName(string? name) => name is not null && FilesByName.TryGetValue(name, out var file)",
        '        ? $"/art/monsters/{file}" : "/art/monsters/monster-001.png";',
        "}",
    ]
    CLIENT_MAP.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(manifest)} monsters")


if __name__ == "__main__":
    main()
