"""Validate weapon art coverage and rebuild lookups without modifying any image."""

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "Game.Client" / "wwwroot" / "art" / "weapons"
MANIFEST = ROOT / "assets" / "weapon-art" / "manifest.json"
SUBJECTS = ROOT / "assets" / "weapon-art" / "subjects.json"
SERVICE = ROOT / "Game.Client" / "Services" / "WeaponArt.cs"


def main() -> None:
    items = json.loads((ROOT / "Game.Server" / "appsettings.json").read_text(encoding="utf-8"))["Weapons"]["Items"]
    existing = {item["code"]: item for item in json.loads(MANIFEST.read_text(encoding="utf-8"))}
    subjects = json.loads(SUBJECTS.read_text(encoding="utf-8"))
    planned = {item["code"]: item for item in subjects}
    if len(planned) != len(subjects):
        raise ValueError("Duplicate individual weapon subjects")
    codes = {item["Code"] for item in items}
    names = {item["Name"] for item in items}
    if len(codes) != len(items) or len(names) != len(items):
        raise ValueError("Duplicate weapon codes or names")
    if set(planned) - codes or codes - (set(existing) | set(planned)):
        raise ValueError(f"Unplanned weapons: missing={codes - (set(existing) | set(planned))}, extra={set(planned) - codes}")

    entries = []
    missing = []
    for item in items:
        code = item["Code"]
        if not re.fullmatch(r"[a-z0-9-]+", code):
            raise ValueError(f"Unsafe weapon code: {code}")
        art = planned.get(code) or existing[code]
        entry = {"code": code, "name": item["Name"], "element": item["Element"],
                 "shape": art["shape"], "file": f"{code}.png",
                 "source": "individual" if code in planned else "master"}
        if code in planned:
            entry.update({key: art[key] for key in ("group", "subject", "palette")})
        entries.append(entry)
        if not (ART / entry["file"]).is_file():
            missing.append(code)
    if missing:
        raise ValueError(f"Missing weapon images: {missing}")

    MANIFEST.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = ["// Generated by tools/build_weapon_manifest.py from the weapon catalog.",
             "namespace Game.Client.Services;", "", "public static class WeaponArt", "{",
             "    private static readonly Dictionary<string, string> CodesByName = new(StringComparer.Ordinal)",
             "    {"]
    lines.extend(f'        ["{item["name"]}"] = "{item["code"]}",' for item in entries)
    lines.extend(["    };", "", '    public static string ForCode(string code) => $"/art/weapons/{code}.png";',
                  "", "    public static string ForName(string name) => CodesByName.TryGetValue(name, out var code)",
                  '        ? ForCode(code) : ForCode("ember-blade");', "}"])
    SERVICE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(entries)} weapons; {len(planned)} individual sprites")


if __name__ == "__main__":
    main()
