"""Validate skill art subjects and generate the client skill-art lookup."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "Game.Server" / "appsettings.json"
SUBJECTS = ROOT / "assets" / "skill-art" / "subjects.json"
MANIFEST = ROOT / "assets" / "skill-art" / "manifest.json"
SERVICE = ROOT / "Game.Client" / "Services" / "SkillArt.cs"


def main() -> None:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    subjects = json.loads(SUBJECTS.read_text(encoding="utf-8"))
    abilities = {item["Code"]: item for item in config["Skills"]["Abilities"]}
    planned = {item["code"]: item for item in subjects}
    if abilities.keys() != planned.keys():
        raise ValueError(f"missing={abilities.keys() - planned.keys()}, extra={planned.keys() - abilities.keys()}")

    entries = []
    for item in subjects:
        ability = abilities[item["code"]]
        entries.append({
            "code": item["code"],
            "name": ability["Name"],
            "profession": ability["ProfessionCode"],
            "file": f"{item['code']}.png",
            "subject": item["subject"],
            "palette": item["palette"],
        })

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = [
        "// Generated by tools/build_skill_manifest.py from the skill catalog.",
        "namespace Game.Client.Services;",
        "",
        "public static class SkillArt",
        "{",
        "    private static readonly HashSet<string> Codes = new(StringComparer.Ordinal)",
        "    {",
    ]
    lines.extend(f'        "{item["code"]}",' for item in entries)
    lines.extend([
        "    };",
        "",
        "    public static string? ForCode(string? code) => code is not null && Codes.Contains(code)",
        "        ? $\"/art/skills/{code}.png\" : null;",
        "}",
    ])
    SERVICE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(entries)} character skills")


if __name__ == "__main__":
    main()
