"""Validate potion/herb subjects against the live catalog and generate client paths."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "Game.Server" / "appsettings.json"
SUBJECTS = ROOT / "assets" / "item-art" / "subjects.json"
MANIFEST = ROOT / "assets" / "item-art" / "manifest.json"
SERVICE = ROOT / "Game.Client" / "Services" / "ItemArt.cs"


def main() -> None:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    subjects = json.loads(SUBJECTS.read_text(encoding="utf-8"))
    catalogs = {
        "potions": {item["Code"]: item for item in config["Consumables"]["Items"]},
        "herbs": {item["Code"]: item for item in config["Materials"]["Items"]
                  if not item["Code"].endswith("-token")},
    }
    entries = []
    for category, catalog in catalogs.items():
        planned = {item["code"]: item for item in subjects[category]}
        if catalog.keys() != planned.keys():
            raise ValueError(f"{category}: missing={catalog.keys() - planned.keys()}, "
                             f"extra={planned.keys() - catalog.keys()}")
        for item in subjects[category]:
            code = item["code"]
            entries.append({"category": category, "code": code,
                            "name": catalog[code]["Name"], "file": f"{code}.png",
                            "subject": item["subject"]})

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = [
        "// Generated by tools/build_item_manifest.py from the item catalog.",
        "namespace Game.Client.Services;",
        "",
        "public static class ItemArt",
        "{",
        "    private static readonly Dictionary<string, string> PathsByCode = new(StringComparer.Ordinal)",
        "    {",
    ]
    for item in entries:
        lines.append(f'        ["{item["code"]}"] = "/art/items/{item["category"]}/{item["file"]}",')
    lines.extend([
        "    };",
        "",
        "    public static string? ForCode(string? code) => code is not null && PathsByCode.TryGetValue(code, out var path)",
        "        ? path : null;",
        "}",
    ])
    SERVICE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(entries)} items ({len(catalogs['potions'])} potions, {len(catalogs['herbs'])} herbs)")


if __name__ == "__main__":
    main()
