"""Validate skill art subjects and generate the client skill-art lookup."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "Game.Server" / "appsettings.json"
SUBJECTS = ROOT / "assets" / "skill-art" / "subjects.json"
MANIFEST = ROOT / "assets" / "skill-art" / "manifest.json"
SERVICE = ROOT / "Game.Client" / "Services" / "SkillArt.cs"


def main() -> None:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    subjects = json.loads(SUBJECTS.read_text(encoding="utf-8"))
    abilities = {item["Code"]: item for item in config["Skills"]["Abilities"]}
    planned = {item["code"]: item for item in subjects}
    missing = abilities.keys() - planned.keys()
    if missing:
        raise ValueError(f"missing={missing}")

    entries = []
    for ability in config["Skills"]["Abilities"]:
        item = planned[ability["Code"]]
        entries.append({
            "code": ability["Code"],
            "name": ability["Name"],
            "profession": ability["ProfessionCode"],
            "file": item.get("file", f"{item['code']}.png"),
            "subject": item["subject"],
            "palette": item["palette"],
        })

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = [
        "// Generated by tools/build_skill_manifest.py from the skill catalog.",
        "namespace Game.Client.Services;",
        "",
        "public static class SkillArt",
        "{",
        "    private static readonly Dictionary<string, string> PathsByCode = new(StringComparer.Ordinal)",
        "    {",
    ]
    lines.extend(f'        ["{item["code"]}"] = "/art/skills/{item["file"]}",' for item in entries)
    lines.extend([
        "    };",
        "",
        "    public static string? ForCode(string? code) => code is not null && PathsByCode.TryGetValue(code, out var path)",
        "        ? path : null;",
        "}",
    ])
    SERVICE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(entries)} character skills")


if __name__ == "__main__":
    main()
