"""Map region hunts and individual dungeons to saved battle backgrounds."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "Game.Client" / "wwwroot" / "art" / "battle-backgrounds"
CATALOG = ROOT / "assets" / "battle-background-art"


def main() -> None:
    world = json.loads((ROOT / "Game.Server" / "world.json").read_text(encoding="utf-8"))["World"]
    regions = {item["Code"]: item for item in world["Regions"]}
    dungeons = {item["Code"]: item for item in world["Dungeons"]}
    subjects = json.loads((CATALOG / "subjects.json").read_text(encoding="utf-8"))
    entries, paths = [], {}
    for item in subjects:
        if Path(item["file"]).name != item["file"] or not (ART / item["file"]).is_file():
            raise ValueError(f"Missing or invalid background: {item['file']}")
        if item["scope"] == "region":
            name = regions[item["code"]]["Name"]
            encounters = [dungeon for dungeon in dungeons.values()
                          if dungeon.get("RegionCode") == item["code"]
                          and dungeon.get("DungeonKind") in ("Hunt", "Elite")]
        elif item["scope"] == "dungeon":
            encounters = [dungeons[item["code"]]]
            name = encounters[0]["Name"]
        else:
            raise ValueError(f"Unknown scope: {item['scope']}")
        if not encounters:
            raise ValueError(f"No encounters for {item['code']}")
        entries.append({**item, "name": name, "encounters": [dungeon["Name"] for dungeon in encounters]})
        for dungeon in encounters:
            if dungeon["Name"] in paths:
                raise ValueError(f"Duplicate background for {dungeon['Name']}")
            paths[dungeon["Name"]] = f"/art/battle-backgrounds/{item['file']}"

    (CATALOG / "manifest.json").write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = ["// Generated by tools/build_battle_background_manifest.py from the world catalog.",
             "namespace Game.Client.Services;", "", "public static class BattleBackgroundArt", "{",
             "    private static readonly Dictionary<string, string> PathsByEncounterName = new(StringComparer.Ordinal)",
             "    {"]
    lines.extend(f'        ["{name}"] = "{path}",' for name, path in paths.items())
    lines.extend(["    };", "", "    public static string? ForEncounter(string? dungeonName) =>",
                  "        dungeonName is not null && PathsByEncounterName.TryGetValue(dungeonName, out var path)",
                  "            ? path : null;", "}"])
    (ROOT / "Game.Client" / "Services" / "BattleBackgroundArt.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Mapped {len(paths)} encounters to {len(entries)} backgrounds")


if __name__ == "__main__":
    main()
